### ISSUE TITLE
Generate QR Codes for Check-in

### ISSUE THREAD

**Issue by RedbackThomson** [UCSDTESC/Check-in#112]
Allow organisers to create a list of QR-codes for their event check-in. Uploading them to S3 automatically so they can easily be linked in emails or downloaded individually.

**Comment by RedbackThomson** [comment]
This should also be linked with #133 so we can send QR codes on the fly if hackers are accepted later than the cut-off date, or if there was an issue delivering the email.

**Comment by subhankar-panda** [comment]
I think it's sufficient to use something like http://goqr.me/api/ instead of generating images on our server and saving them to S3.
