### ISSUE TITLE
Manage old events

### ISSUE THREAD

**Issue by yacoubod** [UCSDTESC/Check-in#4]
would this actually requiring adding any functionality? If you can edit an event before it happened, you can theoretically be able to edit it after the event too if editing isn't automatically disabled.

**Comment by RedbackThomson** [comment]
Editing is supported at all times. Is there anything you would specifically want to edit after an event?

**Comment by RedbackThomson** [comment]
Vague definitions. Editing is always supported for any events regardless of age. Closing this issue.
