### ISSUE TITLE
Adding an Unidentified Column in Users Page for Admin is Broken

### ISSUE THREAD

**Issue by subhankar-panda** [UCSDTESC/Check-in#40]
Looks like the accessor in wrong in the reducer for the ADD_COLUMN event, we should probably do a dropdown to show all possible column headers too

**Comment by RedbackThomson** [comment]
I don't think it's broken since I've been using it for a while. You just have to use the case specific name of the column

**Comment by subhankar-panda** [comment]
Oh I see, I've been typing in "Status" this whole time when it should be "status", should probably do the dropdown in that case

**Comment by RedbackThomson** [comment]
Renamed to better describe the problem

**Comment by RedbackThomson** [comment]
Fixed with #104
