### ISSUE TITLE
Act as an organiser

### ISSUE THREAD

**Issue by yacoubod** [UCSDTESC/Check-in#5]
I think admins should always be able to act as organizers in the sense that they have the same permissions and more. The work will be in creating roles where the organizer role adds limitations.

**Comment by RedbackThomson** [comment]
Currently any Developer (the highest form of Admin) has higher privileges than anyone else. So this shouldn't be a problem.

**Comment by RedbackThomson** [comment]
"Developer" is the highest permission user and can see every event and edit all accounts. Administrators, currently, are only allowed to see their events. Perhaps we should add an extra layer, "Organiser" that acts as the current Administrator role, and make Administrator a more general role.
