### ISSUE TITLE
Add 404 Page To Router

### ISSUE THREAD

**Issue by subhankar-panda** [UCSDTESC/Check-in#67]
I believe there is a [component](https://github.com/UCSDTESC/Check-in/blob/master/src/assets/js/pages/NotFound.js) for it, but it's not used by react-router

**Comment by RedbackThomson** [comment]
This component is not production ready, hence I never put it in. Would be nice to have a custom graphic and a nice layout.

**Comment by kanhegaonkarsaurabh** [comment]
I think I could do this as my first issue. Seems an easy task. What do you mean by a custom graphic? Like a beautified or a better looking 404 page?

**Comment by subhankar-panda** [comment]
Yeah some kind of design - you don't have to make it, we can throw that in later. For now you can just make it look presentable and link it back to the home page

**Comment by kanhegaonkarsaurabh** [comment]
Alright got it. For now, I'll add in the page to the router and then we can create an issue for improving later
