### ISSUE TITLE
'npm install' breaks at node-gyp for Python3+

### ISSUE THREAD

**Issue by kanhegaonkarsaurabh** [UCSDTESC/Check-in#76]
Currently if you clone the repo and install it, the build fails at node-gyp for users who have Python3+ on their machine as node-gyp only supports Python 2.7 for macOS and linux systems.

The fix for this is in this [issue](https://github.com/libxmljs/libxmljs/issues/469#issuecomment-310366815)

Add a note in the README installation to include this warning.

**Comment by RedbackThomson** [comment]
I don't think this is much of an issue for Check-In. node-gyp failures occur basically everywhere it is a dependency, because it uses native build tools. I think rather than us trying to document every possible bug, it is better for developers to look up how to solve their particular problem.
