### ISSUE TITLE
Fix Visual Bug Where Empty Admin UI Loads When Session Expires

### ISSUE THREAD

**Issue by subhankar-panda** [UCSDTESC/Check-in#99]
I believe what happens here is ```loadAllAdminEvents``` fails (as it should), but [the error is just given to console.error](https://github.com/UCSDTESC/Check-in/blob/master/src/assets/js/pages/DashboardPage/index.js#L29) - It would be nice to have either an error message or a redirect to the login page here.

**Comment by RedbackThomson** [comment]
This can probably happen on most pages - each page has its own load into global state. Since the only way to fix this is to create a new session (log back in), I suppose we can just initiate a logout action.
